accounts:
  - name: alice
    coins: ["200000000token"]
  - name: bob
    coins: ["100000000token"]
validator:
  name: alice
  staked: "100000000token"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["100000token"]
